### ISSUE TITLE
watch man error. 

### ISSUE THREAD

**Issue by MehranJanfeshan** [mmazzarolo/react-native-login-animation-example#1]
I am trying to run project on my windows machine and I am getting this error: 

` Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
{"code":"ENOENT","errno":"ENOENT","syscall":"spawn watchman","path":"watchman","spawnargs":["--no-pretty","get-sockname"]}
Error: Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

**Comment by MehranJanfeshan** [comment]
I found the solution, so basically, I needed to uninstall watchman on my machine :)

`npm uninstall watchman -g`
`npm uninstall watchman`
